[package]
name = "harmain-ali/portfolio-website-code"
version = "0.1.0"
description = "My Portfolio"

[dependencies]
"wasmer/static-web-server" = "^1"

[fs]
"/public" = "out"

[[command]]
name = "script"
module = "wasmer/static-web-server:webserver"
runner = "https://webc.org/runner/wasi"

[command.annotations.wasi]
env = ["SERVER_ROOT=/public"]